### PR TITLE
Fix: Add property "overflow: hidden" to the body

### LINKED ISSUE #59: fix: add "overflow: hidden" to the body element
The windows make that the property "overflow: visible" of the body, displays a scroll in x and y. Remove this.
Add the property "overflow: hidden" to the body.

### PR DESCRIPTION
**Pull request by Kehinde13**
this update adds the property "overflow: hidden" to the body element

### CODE REVIEW

**Review by Jes015 — CHANGES_REQUESTED** [review]
Hiii. Could you please remove the `package-lock.json` file. We are using pnpm.

**Comment by Kehinde13** [comment]
Alright

**Comment by Kehinde13** [comment]
hello. i have removed the package-lock.json file

**Comment by Jes015** [comment]
> hello. i have removed the package-lock.json file

Thank u for contributing <3. If you can give a star to the project, would be awesome <3. Thank u <3.

**Comment by Kehinde13** [comment]
Thanks for the opportunity, this is actually my first contributing to open source

**Pull request merged**
